[build]
    publish = ".next"

[[plugins]]
package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    buildDir = ".next"
    changeFreq = "always"
    priority = 0.7
    exclude = ["/privacy-policy", "/terms-of-service"]
    prettyURLs = true