[build]
  publish = ".next"  # Adjust the 'publish' directory to match your project's output folder

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = ".next"
    changeFreq = "daily"
    priority = 0.7
    exclude = ["/privacy-policy", "/terms-of-service"]